steps:
- id: 'Deploy Genesys services in GKE'
  name: 'gcr.io/gcpe0003/privateedition'
  timeout: '3600s'
  env:
    - 'VGCPPROJECT=${_VGCPPROJECT}'
    - 'VGCPREGION=${_VGCPREGION}'
    - 'VGKECLUSTER=${_VGKECLUSTER}'

    - 'VDOMAIN=${_VDOMAIN}'
    - 'VHELMCOMMAND=${_VHELMCOMMAND}'
    - 'VIMAGEREGISTRY=${_VIMAGEREGISTRY}'
    - 'VARTIFACTREPO=${_VARTIFACTREPO}'
    
  script: |
    echo "*** START"
    pwd
    echo "** Environment variables:"
    env
    echo
    echo "** Tools:"
    kubectl version
    helm version
    echo
    echo "**************************"

    echo "** K8s login:"
    export gkeCluster=$VGKECLUSTER
    export gcpRegion=$VGCPREGION
    export gcpProject=$VGCPPROJECT

    gcloud init --no-launch-browser
    gcloud container clusters get-credentials $gkeCluster --region $gcpRegion --project $gcpProject

    echo "**************************"
    echo "** K8s context:"
    kubectl config get-contexts
    echo
    echo "** K8s config:"
    cat ~/.kube/config || true
    echo
    echo "** K8s cluster:"
    kubectl get node
    kubectl top node
    kubectl get ns
    helm ls -n voice
  

timeout: '3600s'
options:
  logging: CLOUD_LOGGING_ONLY